### ISSUE TITLE
Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket

### ISSUE THREAD

**Issue by simonepm** [snowflakedb/snowflake-s3compat-api-test-suite#44]
Hello,

on snowflake-s3compat-api-test-suite latest 2ea0c59 on Mar 23
and MinIO latest RELEASE.2023-04-20T17-56-55Z

I receive the following error for each test:

com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket;

The test are run as follows:

test {
  environment "BUCKET_NAME_1", "test-accessible-bucket"
  environment "END_POINT", "http://localhost:35000"
  environment "NOT_ACCESSIBLE_BUCKET", "test-not-accessible-bucket"
  environment "PAGE_LISTING_TOTAL_SIZE", "1000"
  environment "PREFIX_FOR_PAGE_LISTING", "a/lot/of/files/prefix"
  environment "REGION_1", "default"
  environment "REGION_2", "default"
  environment "S3COMPAT_ACCESS_KEY", "miniouser"
  environment "S3COMPAT_SECRET_KEY", "miniopass"
  useJUnitPlatform()
}

The user is root admin with full access and the exact same parameters work fine with Python boto3 library.

I ended up re-writing part of the tests in Python in order to achieve the result, but I wanted to report this issue here, as well.

![image](https://user-images.githubusercontent.com/44468150/234513395-bf343458-2ea6-4f63-b2f5-3339fa61ba67.png)
![image](https://user-images.githubusercontent.com/44468150/234513534-c25c25db-e5b9-4d2a-be64-aff2221954d0.png)
![image](https://user-images.githubusercontent.com/44468150/234513621-77b9a23f-a103-4917-ae00-95ca53091b38.png)

**Comment by sfc-gh-schen** [comment]
@simonepm Thanks for reporting this. I notice you are using localhost with a port number. Please note that this test repo quires the endpoint to be public.

**Comment by simonepm** [comment]
Thanks for confirming that!

We are now exposing MinIO from a public web https endpoint called
https://abcd-s3.wxyz.com
but we receive the same
Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket;

test {

...
environment "BUCKET_NAME_1", "abcd-s3"
environment "END_POINT", "wxyz.com"
...
}

**Comment by sfc-gh-schen** [comment]
@simonepm Great! Yes, we want it to be virtual host style.

**Comment by sfc-gh-schen** [comment]
Close as it is not the repo problem.
