### ISSUE TITLE
Is Path Style Supported?

### ISSUE THREAD

**Issue by username-is-already-taken2** [snowflakedb/snowflake-s3compat-api-test-suite#45]
Hi there

Our cloudian instance is setup path style `<ENDPOINT>/<BUCKET>` vs virtual host style `<BUCKET>.<ENDPOINT>`

Does snowflake only support virtual host style?

![image](https://github.com/snowflakedb/snowflake-s3compat-api-test-suite/assets/13700297/b4e74624-46a8-4b5b-b7b9-6052b4a27153)

I can get round it by creating valid dns records for the bucket we want to register in our snowflake account but I our SSL certificate is not setup to support that url structure, so I would like to check before going down that route.

Apart from the SSL test, the other failures look to be covered by your troubleshooting section, do you think there is anything else for concern? 

Thank you

Gary

**Comment by sfc-gh-schen** [comment]
Sorry. No. We require host style.
